import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import AuthProvider from "./auth/provider";
import { Footer } from "./components/footer";
import { Navigation } from "./components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavBar />
          <div className="flex flex-1 h-[90vh]">
            <main className="flex-1">{children}</main>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}